import React, { useState } from "react";
import { X, Copy, Check, FolderOpen, Monitor, Apple } from "lucide-react";

interface AdobePathGuideModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const AdobePathGuideModal: React.FC<AdobePathGuideModalProps> = ({ isOpen, onClose }) => {
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<"premiere" | "media_encoder" | "after_effects">("premiere");

  if (!isOpen) return null;

  const paths = {
    premiere: {
      title: "Adobe Premiere Pro - Presets Directory",
      win: `%USERPROFILE%\\Documents\\Adobe\\Premiere Pro\\[Version]\\Profile-[Name]\\Settings\\Presets`,
      mac: `~/Documents/Adobe/Premiere Pro/[Version]/Profile-[Name]/Settings/Presets`,
      instructions: [
        "Open Premiere Pro and locate the 'Presets' window panel.",
        "Right-click inside the Presets list and choose 'Import Presets...'",
        "Select the downloaded .epr file generated by PresetCraft AI.",
        "Alternatively, copy the .epr file directly into the system directory path specified above.",
      ],
    },
    media_encoder: {
      title: "Adobe Media Encoder - Export Presets Directory",
      win: `%USERPROFILE%\\Documents\\Adobe\\Adobe Media Encoder\\[Version]\\Presets`,
      mac: `~/Documents/Adobe/Adobe Media Encoder/[Version]/Presets`,
      instructions: [
        "Launch Adobe Media Encoder.",
        "In the 'Preset Browser' panel, click the '+' icon and choose 'Import Presets...'",
        "Or simply drag and drop the downloaded .epr file directly into Media Encoder.",
        "The preset will now be available for all future batch renders.",
      ],
    },
    after_effects: {
      title: "Adobe After Effects - Render Queue Script (.jsx)",
      win: `C:\\Program Files\\Adobe\\Adobe After Effects [Version]\\Support Files\\Scripts`,
      mac: `/Applications/Adobe After Effects [Version]/Scripts`,
      instructions: [
        "Open your active composition project in Adobe After Effects.",
        "Navigate to top menu: File -> Scripts -> Run Script File...",
        "Select the downloaded .jsx file from PresetCraft AI.",
        "The script will configure your Render Queue with exact resolution, framerate, and bitrate settings.",
      ],
    },
  };

  const copyToClipboard = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const currentInfo = paths[activeTab];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/90 backdrop-blur-md animate-fade-in">
      <div className="bg-[#111111] border-2 border-white/20 rounded-xl max-w-2xl w-full p-6 sm:p-8 shadow-2xl relative max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-white/10">
          <div className="flex items-center space-x-3">
            <div className="p-2 rounded-lg bg-black border border-white/20 text-[#00FF41]">
              <FolderOpen className="w-5 h-5" />
            </div>
            <div>
              <div className="text-[10px] font-black font-mono uppercase tracking-widest text-[#00FF41]">System Path Guide</div>
              <h3 className="text-xl font-black font-display uppercase tracking-tight text-white">
                Adobe Preset Target Directories
              </h3>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-full border border-white/20 text-white/50 hover:text-white hover:bg-white/10 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Software Selector Tabs */}
        <div className="flex border-b border-white/10 mt-6 font-mono text-xs uppercase font-bold">
          <button
            onClick={() => setActiveTab("premiere")}
            className={`px-4 py-3 transition-all border-b-2 cursor-pointer ${
              activeTab === "premiere"
                ? "border-[#00FF41] text-[#00FF41] bg-white/5"
                : "border-transparent text-white/40 hover:text-white"
            }`}
          >
            Premiere (.EPR)
          </button>
          <button
            onClick={() => setActiveTab("media_encoder")}
            className={`px-4 py-3 transition-all border-b-2 cursor-pointer ${
              activeTab === "media_encoder"
                ? "border-[#00FF41] text-[#00FF41] bg-white/5"
                : "border-transparent text-white/40 hover:text-white"
            }`}
          >
            Media Encoder (.EPR)
          </button>
          <button
            onClick={() => setActiveTab("after_effects")}
            className={`px-4 py-3 transition-all border-b-2 cursor-pointer ${
              activeTab === "after_effects"
                ? "border-[#00FF41] text-[#00FF41] bg-white/5"
                : "border-transparent text-white/40 hover:text-white"
            }`}
          >
            After Effects (.JSX)
          </button>
        </div>

        {/* Tab Content */}
        <div className="mt-6 space-y-6">
          <h4 className="text-base font-black font-display uppercase tracking-tight text-white">{currentInfo.title}</h4>

          {/* Windows Path */}
          <div className="p-4 rounded-xl bg-black border border-white/20">
            <div className="flex items-center justify-between mb-2 font-mono">
              <span className="text-xs font-bold text-white flex items-center gap-1.5 uppercase">
                <Monitor className="w-3.5 h-3.5 text-[#00FF41]" />
                Windows Path:
              </span>
              <button
                onClick={() => copyToClipboard(currentInfo.win, "win")}
                className="text-xs font-bold text-[#00FF41] hover:underline flex items-center gap-1 cursor-pointer uppercase"
              >
                {copiedKey === "win" ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-[#00FF41]" />
                    <span>Copied!</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5" />
                    <span>Copy Path</span>
                  </>
                )}
              </button>
            </div>
            <code className="text-xs font-mono text-[#00FF41] break-all select-all block bg-[#151515] p-3 rounded border border-white/10">
              {currentInfo.win}
            </code>
          </div>

          {/* macOS Path */}
          <div className="p-4 rounded-xl bg-black border border-white/20">
            <div className="flex items-center justify-between mb-2 font-mono">
              <span className="text-xs font-bold text-white flex items-center gap-1.5 uppercase">
                <Apple className="w-3.5 h-3.5 text-white" />
                macOS Path:
              </span>
              <button
                onClick={() => copyToClipboard(currentInfo.mac, "mac")}
                className="text-xs font-bold text-[#00FF41] hover:underline flex items-center gap-1 cursor-pointer uppercase"
              >
                {copiedKey === "mac" ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-[#00FF41]" />
                    <span>Copied!</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5" />
                    <span>Copy Path</span>
                  </>
                )}
              </button>
            </div>
            <code className="text-xs font-mono text-[#00FF41] break-all select-all block bg-[#151515] p-3 rounded border border-white/10">
              {currentInfo.mac}
            </code>
          </div>

          {/* Step-by-step instructions */}
          <div className="p-5 rounded-xl bg-[#151515] border border-white/10">
            <h5 className="text-xs font-black font-mono text-white/60 uppercase tracking-widest mb-3">
              Installation Procedure:
            </h5>
            <ol className="space-y-2.5 font-mono text-xs text-white/80 uppercase">
              {currentInfo.instructions.map((step, idx) => (
                <li key={idx} className="flex items-start gap-3">
                  <span className="w-5 h-5 rounded bg-[#00FF41] text-black font-black flex items-center justify-center text-[10px] flex-shrink-0 mt-0.5">
                    {idx + 1}
                  </span>
                  <span>{step}</span>
                </li>
              ))}
            </ol>
          </div>
        </div>

        {/* Modal Footer */}
        <div className="mt-8 pt-4 border-t border-white/10 flex justify-end">
          <button
            onClick={onClose}
            className="px-6 py-3 rounded-full bg-[#00FF41] hover:bg-[#00FF41]/90 text-black font-mono font-black text-xs uppercase tracking-widest cursor-pointer transition-all"
          >
            Acknowledge & Close
          </button>
        </div>
      </div>
    </div>
  );
};

